### ISSUE TITLE
Hung ctrl key in Windows

### ISSUE THREAD

**Issue by jmwerner** [randy3k/R-Box#68]
Hey Randy,

When sending code from sublime text to cygwin the computer will act as if the 'ctrl' key is being held until I press it again to, in effect, turn itself off. This happens when I send code to cygwin AND it completes execution in cygwin. When I'm waiting for the chunk of code to finish running in cygwin, and start clicking around, it behaves normally and does not act as if 'ctrl' is being held after code finishes execution or during execution. I've never had any other issues with this machine and the issue has been replicated with a different keyboard too.

Thanks!

Windows 7, ST3, Cygwin64

**Comment by randy3k** [comment]
Hi Jeremy,

I am quite sure it is an issue of AutoHotKey (an automation scripting program on Windows).

Could you try holding the control key a bit longer before releasing it? It may be because the control key is released before the AutoHotKey program finishes. And AutoHotKey keeps the key in the "pressed" status.

I currently don't have an access of a Windows machine, will fix it later.

**Comment by jmwerner** [comment]
That seems very plausible, when I very quickly release 'ctrl' I reproduce the error every time but when I hold it for 1 second or more before releasing the error does not happen.

**Comment by randy3k** [comment]
Jeremy,

I guess it has been fixed in [SendText+](https://github.com/randy3k/SendTextPlus).
