### ISSUE TITLE
Key bind for  "<-" within an R script when using sublime and R-box.  

### ISSUE THREAD

**Issue by jrzaurin** [randy3k/R-Box#71]
I am not entirely sure this is the correct place, since the question is fairly general, but I guess someone here might know the answer. 

I am trying to bind `Ctrl+-`  to `<-` JUST within an R script when using R-box (similar to the behaviour when using ESS in Emacs).

Thanks in advance for your time.

**Comment by mikedecr** [comment]
I made one of these for myself using a different keyboard shortcut. You could grab the code and paste this into your user keymap file with any modifications to the keyboard shortcut you need. 

    // Assignment operator with [ super + shift + , ]
	{
		"keys":["super+shift+,"],
		"context":
		[
			{"key": "selector",
			"operator": "equal",
			"operand": "source.r"}
		],
		"command": "insert_snippet",
		"args": {"contents": "<- $0"}
	}

And this next bit would delete the entire assignment operator with one press of backspace instead of two: 

    //delete the assignment operator with one key press
	{
		"keys": ["backspace"],
		"context":
		[
			{ "key": "selector",
				"operator": "equal",
				"operand": "source.r" },
			{ "key": "selection_empty",
				"operator": "equal",
				"operand": true,
				"match_all": true },
			{ "key": "preceding_text",
				"operator": "regex_contains",
				"operand": "<-$",
				"match_all": true }
		],
		"command": "run_macro_file",
		"args": { "file": "Packages/User/macros/Delete Two Left.hidden-sublime-macro" }
	}

You will need to specify the pathway to the macro for your own machine. The "Delete Two Left" macro I think I got from the `LaTeXTools` package and just pasted it into my user folder, but I'm not 100% sure about that. If your machine doesn't already have a copy of it (e.g. with the Default package with Sublime) then you can create this macro yourself. The macro file only contains

    [
	   { "command": "left_delete" },
	   { "command": "left_delete" }
    ]

so you could paste that into sublime, save it with whatever file name you want and the correct file extension.

**Comment by jrzaurin** [comment]
wow Mike

Many thanks for the details! works perfectly
